AWSTemplateFormatVersion: 2010-09-09
Description: A cloudFormation template to create secrets for gateway deployment.

Parameters:
  ProjectName:
    Type: String
    Default: portkey
    AllowedPattern: ".+"
    ConstraintDescription: Must not be empty

  Environment:
    Type: String
    Default: dev
    AllowedPattern: ".+"
    Description: Environment for which the resources are being created. e.g., prod, dev, test etc.
    ConstraintDescription: Must not be empty

  DockerUsername:
    Description: Enter the docker username provided by the portkey.
    Type: String
    AllowedPattern: ".+"

  DockerPassword:
    Description: Enter the docker password provided by the portkey.
    Type: String
    NoEcho: true
    AllowedPattern: ".+"

  PortkeyClientAuth:
    Description: Enter portkey client auth provided by the portkey.
    Type: String
    NoEcho: true
    AllowedPattern: ".+"
  
  Organizations:
    Description: Provide a comma separated list of Organizations IDs to be synced.
    Type: String
    AllowedPattern: ".+"
  
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Project Details"
        Parameters: 
          - ProjectName
          - Environment
      - 
        Label: 
          default: "Configure Image Credentials"
        Parameters: 
          - DockerUsername
          - DockerPassword
      - 
        Label: 
          default: "Portkey Integration"
        Parameters: 
          - PortkeyClientAuth
          - Organizations
    ParameterLabels:
      DockerUsername:
        default: Docker Username
      DockerPassword: 
        default: Docker Password
      ProjectName: 
        default: Provide a name for the project
      Environment:
        default: Provide the environment name
      Organizations: 
        default: Organizations
      PortkeyClientAuth:
        default: Portkey Client Auth

Resources:
  DockerCredentialsSecret: 
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Stores the docker credentials for Portkey gateway image repository.
      Name: !Sub ${ProjectName}/${Environment}/docker-credentials
      SecretString: !Sub '{"username":"${DockerUsername}","password":"${DockerPassword}"}'
      Tags: 
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
  
  LicenseSecret: 
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Stores the portkey client auth and organisations to be synced.
      Name: !Sub ${ProjectName}/${Environment}/clientauth-organizations
      SecretString: !Sub '{"PORTKEY_CLIENT_AUTH":"${PortkeyClientAuth}","ORGANISATIONS_TO_SYNC":"${Organizations}"}'
      Tags: 
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
  

Outputs:
  DockerCredentialsSecretArn:
    Value: !GetAtt  DockerCredentialsSecret.Id
  ClientOrgSecretNameArn:
    Value: !GetAtt LicenseSecret.Id


  